# Generated by Django 3.1.3 on 2021-05-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['from_user', 'to_user', '-created_at']},
        ),
    ]
