# Generated by Django 3.1.3 on 2021-05-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_auto_20210523_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at']},
        ),
    ]
