# Generated by Django 3.2.4 on 2021-06-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('tweet', 'created_at')},
        ),
    ]
