# Generated by Django 3.1.3 on 2021-05-23 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='newsfeed',
            index_together={('user', 'created_at')},
        ),
    ]
