FOLLOWING_PATTERN = 'following:{user_id}'
USER_PATTERN = 'user:{user_id}'
USER_PROFILE_PATTERN = 'userprofile:{user_id}'
USER_TWEET_PATTERN = 'usertweet:{user_id}'
USER_NEWSFEED_PATTERN = 'usernewsfeed:{user_id}'
